name: Delete All Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete all workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUNS=$(gh api -X GET repos/${{ github.repository }}/actions/runs --paginate -q ".workflow_runs[] | select(.id != ${{ github.run_id }}) | .id")
          
          for run_id in $RUNS; do
            echo "Deleting run ID: $run_id"
            gh api -X DELETE repos/${{ github.repository }}/actions/runs/$run_id
          done