name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:     

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write      
      contents: read
    steps:
      - name: Delete workflow runs older than 1 day
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1         
          keep_minimum_runs: 3    
